<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\UndefinedCRM.Communication\UndefinedCRM.Communication.csproj" />
      <ProjectReference Include="..\UndefinedCRM.Domain\UndefinedCRM.Domain.csproj" />
      <ProjectReference Include="..\UndefinedCRM.Exception\UndefinedCRM.Exception.csproj" />
      <ProjectReference Include="..\UndefinedCRM.Infrastructure\UndefinedCRM.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.0.0-preview1" />
      <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
        <HintPath>..\..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.13\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
